### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by skysoftgmbh** [tdoescher/contao-googlemaps-bundle#1]
Hey,

would be nice to get a short manual how to use this add-on.

Thanks

**Comment by tdoescher** [comment]
Two new content elements are made available:

Firstly, the Google Maps Embed Element, which outputs a map by specifying an API key, the address and the zoom level using the Google Maps Embed API.

Alternatively, there is the Google Maps HTML element, which is used to output a map using the Google Maps JavaScript API, simply enter the code displayed by Google. This could also be created using the standard Contao HTML element or using a template file.
